// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWr66AqdTzf7SGGRGpVViNWAZNfUnOkOk',
    appId: '1:192209085621:web:74ed80e725982a4d588afc',
    messagingSenderId: '192209085621',
    projectId: 'instax-6eeb2',
    authDomain: 'instax-6eeb2.firebaseapp.com',
    storageBucket: 'instax-6eeb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9w3u4oAi5jpXIFearDuV0czOeatO6Ibs',
    appId: '1:192209085621:android:3ed21bab29e106ae588afc',
    messagingSenderId: '192209085621',
    projectId: 'instax-6eeb2',
    storageBucket: 'instax-6eeb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsYHUQh4knIsPC3AghGtvbFgH2jeP_nHs',
    appId: '1:192209085621:ios:a1f08d733fa6c1b1588afc',
    messagingSenderId: '192209085621',
    projectId: 'instax-6eeb2',
    storageBucket: 'instax-6eeb2.appspot.com',
    iosBundleId: 'com.example.reminderApp',
  );
}
